apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: metrics-agent-creator
spec:
  name: metrics-agent-creator
  documentation: |
    Sets up a victoria metrics agent for shipping metrics, pairs with `prom-creator`
  creates:
    templates:
    - source: resources/monitoring/helm
      destination: "helm/monitoring"
      external: false
    - source: resources/monitoring/mgmt.yaml
      destination: "bootstrap/monitoring/mgmt.yaml"
      external: false
  scmConnectionRef:
    name: github  # you'll need to add this ScmConnection manually before this is functional
  title: "Setup prometheus agent for metrics shipping"
  message: "Setup prometheus agent for metrics shipping"
  identifier: [[ .Identifier ]] # REPLACEME with your own repo slug
  branch: [[ or .Context.Branch "main" ]]
  configuration:
  - name: cluster
    type: STRING
    documentation: CRD name for this cluster, use `mgmt` to place it in the management cluster
  - name: host
    type: STRING
    documentation: the FQDN of your victoria metrics prometheus instance
  - name: tagName
    type: STRING
    documentation: The cluster tag name you want to use to control the global service for installation of prometheus agent
  - name: tagValue
    type: STRING
    documentation: The cluster tag value you want to use to control the global service for installation of prometheus agent 
