apiVersion: deployments.plural.sh/v1alpha1
kind: InfrastructureStack
metadata:
  name: core-infra
spec:
  name: core-infra
  detach: false
  type: TERRAFORM
  approval: true
  manageState: true
  actor: console@plural.sh
  repositoryRef:
    name: infra
    namespace: infra
  clusterRef:
    name: mgmt
    namespace: infra
  variables:
    project: [[ .Project ]]
    region: [[ .Region ]]
    cluster_name: [[ .Cluster ]]
  [[ if eq .Provider "azure" ]]
    resource_group_name: [[ .Project ]]
  environment:
    - name: ARM_USE_OIDC
      value: "true"
    - name: ARM_USE_CLI
      value: "false"
    - name: ARM_OIDC_TOKEN_FILE_PATH
      value: "/var/run/secrets/azure/tokens/azure-identity-token"
    - name: ARM_CLIENT_ID
      value: {{ .StacksIdentity }}
    - name: ARM_TENANT_ID
      value: [[ .Context.TenantId ]]
    - name: ARM_SUBSCRIPTION_ID
      value: [[ .Context.SubscriptionId ]]
  jobSpec:
    namespace: plrl-deploy-operator
    labels:
      azure.workload.identity/use: "true"
    serviceAccount: "stacks"
  [[ end ]]
  git:
    ref: main
    folder: terraform/core-infra