apiVersion: deployments.plural.sh/v1alpha1
kind: InfrastructureStack
metadata:
  name: core-infra
spec:
  name: core-infra
  detach: false
  type: TERRAFORM
  approval: true
  manageState: true
  actor: console@plural.sh
  repositoryRef:
    name: infra
    namespace: infra
  clusterRef:
    name: mgmt
    namespace: infra
  variables:
    project: [[ .Project ]]
    region: [[ .Region ]]
    cluster_name: [[ .Cluster ]]
  git:
    ref: main
    folder: terraform/core-infra