apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: policy-bundle
spec:
  template:
    name: policy-bundle
    namespace: policy
    git:
      folder: resources/policy/bundles/{{ context.bundle }}
      ref: main
    repositoryRef:
      kind: GitRepository
      name: infra
      namespace: infra