apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: opa-constraints
  namespace: policy
spec:
  namespace: policy
  templated: false
  git:
    folder: resources/policy/constraints
    ref: main
  repositoryRef:
    kind: GitRepository
    name: bootstrap
    namespace: policy
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra