apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: gatekeeper
  namespace: policy
spec:
  namespace: policy
  helm:
    version: 3.15.1
    chart: gatekeeper
    repository:
      name: gatekeeper
      namespace: policy
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra
---
apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
 name: gatekeeper
 namespace: policy
spec:
 serviceRef:
   name: gatekeeper
   namespace: policy