apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: cert-manager
  namespace: infra
spec:
  namespace: cert-manager
  git:
    folder: helm-values
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  helm:
    version: "v1.x.x"
    chart: cert-manager
    url: https://charts.jetstack.io
    valuesFiles:
    - certmanager.yaml
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra