apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: flux
  namespace: infra
spec:
  namespace: flux
  git:
    folder: helm-values
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  helm:
    version: "2.14.0"
    chart: flux2
    url: https://fluxcd-community.github.io/helm-charts
    valuesFiles:
    - flux.yaml
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra