apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: cert-manager
  namespace: infra
spec:
  namespace: cert-manager
  git:
    folder: helm-values
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  helm:
    version: "v1.13.3"
    chart: cert-manager
    url: https://charts.jetstack.io
    valuesFiles:
    - certmanager.yaml
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra
{{ if not .Cloud }}
---
apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: flux
  namespace: infra
spec:
  namespace: flux
  git:
    folder: helm-values
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  helm:
    version: "2.12.2"
    chart: flux2
    url: https://fluxcd-community.github.io/helm-charts
    valuesFiles:
    - flux.yaml
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra
---
apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: runtime
  namespace: infra
spec:
  namespace: plural-runtime
  git:
    folder: helm-values
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  helm:
    version: "0.x.x"
    chart: runtime
    url: https://pluralsh.github.io/bootstrap
    valuesFiles:
    - runtime.yaml
    repository:
      namespace: infra
      name: runtime
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra
{{ end }}
