apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: runtime
  namespace: infra
spec:
  namespace: plural-runtime
  git:
    folder: helm-values
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  helm:
    version: "0.x.x"
    chart: runtime
    valuesFiles:
    - runtime.yaml
    repository:
      namespace: infra
      name: runtime
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra
