apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: runtime
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  interval: 5m0s
  url: https://pluralsh.github.io/bootstrap