apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: runtime
  namespace: infra
spec:
  interval: 5m0s
  url: https://pluralsh.github.io/bootstrap
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: infra
spec:
  interval: 5m0s
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flux
  namespace: infra
spec:
  interval: 5m0s
  url: https://fluxcd-community.github.io/helm-charts