apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  interval: 5m0s
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flagger
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  interval: 5m0s
  url: https://flagger.app
