apiVersion: v1
kind: Secret
metadata:
  name: plural-env
stringData:
  PLURAL_ACCESS_TOKEN: {{ .Values.pluralToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: acme-eab-secret
  namespace: {{ .Values.certManagerNamespace | default .Release.Namespace }}
stringData:
  eab-secret: {{ .Values.acmeEAB.secret }}
