apiVersion: deployments.plural.sh/v1alpha1
kind: GitRepository
metadata:
  name: policy
  namespace: plrl-policy
spec:
  url: {{ configuration.repoUrl }}
---
apiVersion: deployments.plural.sh/v1alpha1
kind: Cluster
metadata:
  name: mgmt
  namespace: plrl-policy
spec:
  handle: mgmt