apiVersion: v2
name: runtime
description: Sets up the basic dependencies needed to get a network stack running
type: application
version: 0.1.2
appVersion: "1.16.0"
dependencies:
- name: external-dns
  version: 6.14.5
  repository: https://charts.bitnami.com/bitnami
  condition: external-dns.enabled
- name: cert-manager
  version: v1.13.3
  repository: https://charts.jetstack.io
  condition: cert-manager.enabled
- name: plural-certmanager-webhook
  version: 0.1.7
- name: ingress-nginx
  version: 4.8.3
  repository: https://kubernetes.github.io/ingress-nginx
  condition: ingress-nginx.enabled
- name: ingress-nginx
  version: 4.8.3
  repository: https://kubernetes.github.io/ingress-nginx
  alias: ingress-nginx-private
  condition: ingress-nginx-private.enabled
- name: flux2
  repository: https://fluxcd-community.github.io/helm-charts
  version: 2.11.1