apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  annotations:
    description: Disallows the creation of resources using a default service account.
      Has no effect during audit.
    metadata.gatekeeper.sh/title: Block Creation with Default Service Account
  labels:
    app.kubernetes.io/managed-by: deployments.plural.sh
  name: k8sblockcreationwithdefaultserviceaccount
spec:
  crd:
    spec:
      names:
        kind: K8sBlockCreationWithDefaultServiceAccount
      validation:
        legacySchema: false
  targets:
  - rego: |
      package k8sblockcreationwithdefaultserviceaccount

      violation[{"msg": msg}] {
        input.review.operation == "CREATE"
        username := object.get(input.review.userInfo, "username", "")
        startswith(username, "system:serviceaccount:")
        endswith(username, ":default")
        msg := "Creation is blocked with default service account."
      }
    target: admission.k8s.gatekeeper.sh
