installCRDs: true
serviceAccount:
  name: cert-manager
  annotations:
    plural.sh/dummy: 'ignore'
  # azure.workload.identity/client-id: 027c5496-d46b-40d3-8f92-a0f44dcf3500 # uncomment and update for azure

securityContext:
  fsGroup: 1000
  runAsNonRoot: true

podLabels:
  azure.workload.identity/use: "true"