helmController:
  create: false
imageAutomationController:
  create: false
imageReflectionController:
  create: false
kustomizeController:
  create: false
notificationController:
  create: false
sourceController:
  create: true
policies:
  create: false