apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: console
  namespace: infra
spec:
  namespace: plrl-console
  git:
    folder: helm-values
    ref: [[ or .Context.Branch "main" ]]
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  helm:
    version: "0.x.x"
    chart: console
    url: https://pluralsh.github.io/console
    valuesFiles:
    - console.yaml
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra
