apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: rbac
spec:
  template:
    name: rbac
    namespace: rbac
    git:
      folder: services/rbac
      ref: [[ or .Context.Branch "main" ]]
    repositoryRef:
      kind: GitRepository
      name: infra
      namespace: infra
    
